"""add owning user id to playbook

Revision ID: 091c94ac5d24
Revises: 7d533bd31757
Create Date: 2025-03-30 17:31:14.262792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '091c94ac5d24'
down_revision = '7d533bd31757'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owning_user_id', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_column('owning_user_id')

    # ### end Alembic commands ###
