"""add owning user id to move

Revision ID: d2be64cfb704
Revises: 091c94ac5d24
Create Date: 2025-04-15 17:16:17.257348

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2be64cfb704'
down_revision = '091c94ac5d24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owning_user_id', sa.String(length=32), nullable=False))
        batch_op.create_foreign_key(None, 'users', ['owning_user_id'], ['id'])

    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.alter_column('owning_user_id',
               existing_type=mysql.VARCHAR(length=100),
               type_=sa.String(length=32),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'users', ['owning_user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('playbooks', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('owning_user_id',
               existing_type=sa.String(length=32),
               type_=mysql.VARCHAR(length=100),
               existing_nullable=False)

    with op.batch_alter_table('moves', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owning_user_id')

    # ### end Alembic commands ###
